export type HospitalFunded = {
  id: string;
  hospitalRequestId: string;
  hospital: string;
  orderID: string;
  equipmentShipped: boolean;
  fundingCompleted: number;
  funders: string;
  corporateFunding: string;
  thankYouNote: string;
  fundedPicture1: string;
  fundedPicture2: string;
  fundedPicture3: string;
  fundedPicture4: string;
  fundedPicture5: string;
  impactPicture1: string;
  impactPicture2: string;
  impactPicture3: string;
  impactPicture4: string;
  impactPicture5: string;
  shortThankYou: string;
  thankYouNoteTitle: string;
  impactTitle: string;
};
